### ISSUE TITLE
开启后b站很容易炸

### ISSUE THREAD

**Issue by 2333tracy** [eric2788/tempermonkey-scripts#1]
![image](https://user-images.githubusercontent.com/58852317/142382166-b9b5d51e-34fc-4379-9fa4-e700487b97eb.png)
开启后过一段时间就出现了，测试了好几次都这样

**Comment by eric2788** [comment]
1. 哪個腳本
2. 做了什麼之後會爆炸

**Comment by eric2788** [comment]
如果你指的是录制脚本的话，你是录制了多久才炸的

**Comment by eric2788** [comment]
更新了 v0.3 版本，试试看？
如果还是有问题的话，重开一下这个 issue

**Comment by 2333tracy** [comment]
> 如果你指的是录制脚本的话，你是录制了多久才炸的

是录制脚本，但没有录制

> 更新了 v0.3 版本，试试看？ 如果还是有问题的话，重开一下这个 issue

还是有问题，又炸了

开启脚本后没有开启录制，就正常看直播，然后过一段时间就炸了
![image](https://user-images.githubusercontent.com/58852317/142485581-d4a15046-7427-4ce6-88a7-406c459126d3.png)
不知道是不是和其他脚本有兼容问题
我目前同时开启的和b站有关的脚本有
1.https://greasyfork.org/zh-CN/scripts/429068-bilibili-%E6%9E%9D%E7%BD%91%E6%9F%A5%E9%87%8D-api-%E7%89%88
2.https://greasyfork.org/zh-CN/scripts/372516-bilibili-merged-flv-mp4-ass-enhance
3.https://greasyfork.org/zh-CN/scripts/381682-html5%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8%E5%A2%9E%E5%BC%BA%E8%84%9A%E6%9C%AC
4.https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6

**Comment by eric2788** [comment]
是安裝了這個腳本之後才開始有這個問題？
那試試下面所有的東西
1 打開f12的console後再打開網頁看有沒有錯誤
2 拔除所有腳本逐個排查
3 換瀏覽器看看

**Comment by eric2788** [comment]
因為如果你沒開啟錄製，這個腳本除了獲取線路地址和放按鈕元素到網頁內之外啥都不會做，照計應該沒有會爆炸的元素

**Comment by 2333tracy** [comment]
> 是安裝了這個腳本之後才開始有這個問題？ 那試試下面所有的東西 1 打開f12的console後再打開網頁看有沒有錯誤 2 拔除所有腳本逐個排查 3 換瀏覽器看看

是的，而且只有在开启了这个之后才会出现这个问题

换了个浏览器，这个浏览器没装其他的脚本，先f12测试了一下
![image](https://user-images.githubusercontent.com/58852317/142575540-f51cee30-a484-4b08-abc7-89dfa3ab1a43.png)
运行一段时间后
![image](https://user-images.githubusercontent.com/58852317/142575885-93cf1107-8ad9-4ef4-aea3-6ef6eec167d3.png)
然后就炸了orz

**Comment by eric2788** [comment]
> 
> 
> > 是安裝了這個腳本之後才開始有這個問題？ 那試試下面所有的東西 1 打開f12的console後再打開網頁看有沒有錯誤 2 拔除所有腳本逐個排查 3 換瀏覽器看看
> 
> 是的，而且只有在开启了这个之后才会出现这个问题
> 
> 换了个浏览器，这个浏览器没装其他的脚本，先f12测试了一下 ![image](https://user-images.githubusercontent.com/58852317/142575540-f51cee30-a484-4b08-abc7-89dfa3ab1a43.png) 运行一段时间后 ![image](https://user-images.githubusercontent.com/58852317/142575885-93cf1107-8ad9-4ef4-aea3-6ef6eec167d3.png) 然后就炸了orz

这个 syntax error 是属于浏览器 js 版本过低了

**Comment by eric2788** [comment]
另外腳本出錯之後正常就會停止執行該腳本，之後的東西應該與它無關才對 🤔

**Comment by 2333tracy** [comment]
我更新一下浏览器试试？

**Comment by eric2788** [comment]
试试更新浏览器，或者用最新版chrome

**Comment by 2333tracy** [comment]
更新了浏览器之后好像就没问题了_(:з」∠)_

**Comment by 2333tracy** [comment]
![image](https://user-images.githubusercontent.com/58852317/142606383-de524a2c-e977-40e6-ba41-f0cd7e7b3f8a.png)
难顶，过一段时间又出现了

**Comment by eric2788** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/58852317/142606383-de524a2c-e977-40e6-ba41-f0cd7e7b3f8a.png) 难顶，过一段时间又出现了

F12 有什么错误？

另外你试试最新版 chrome 看看

**Comment by eric2788** [comment]
再有任何补充告诉我，你会不会是用了暴力猴之类的，我这个支援的是T猴
