### ISSUE TITLE
嘗試改寫同傳插件裏的SC記錄小功能為油猴腳本

### ISSUE THREAD

**Issue by Nuhcnam** [eric2788/tempermonkey-scripts#10]
老師您好。B站取消了SuperChat功能裏的留言榜，對查看直播中的歷史SC造成很多不便。我幾番搜索後找到您寫的同傳插件裏有相關腳本（https://github.com/eric2788/bilibili-jimaku-filter/blob/master/src/superchat.js），不過我主要看的是國V，用不上這個插件大部分的功能。我用自己很基礎的編程能力，嘗試過把這個小功能單獨抽出來可惜總是失敗。如果您有空，請問可以把它改寫成一個油猴腳本嗎？謝謝。

**Comment by eric2788** [comment]
你可以試試自己搞一個，用 xfgryujk 大佬的bliveproxy 捕捉 superchat

**Comment by Nuhcnam** [comment]
謝謝回覆！我不是很熟悉websocket，所以看了一會資料。
按使用例子，目前寫出這樣的東西：

(function() {
  // 醒目留言
  bliveproxy.addCommandHandler('SUPER_CHAT_MESSAGE', command => {
    let data = command.data
    // console.log(data)
    let details = {
        uid: data.uid,
        username: data.user_info.uname,
        price: data.price,
        message: data.message,
        timer: data.start_time
    }
    console.log(details)
  })
})();

但由於@run-at document-start，似乎不能用document.createElement( )的方法把details寫到一個空白框裏，對嗎？想請老師再次指點。

**Comment by eric2788** [comment]
應該沒關係吧，不然你也可以收到sc之後再create

**Comment by Nuhcnam** [comment]
感謝指路！搞定了！我自己寫的腳本可以不加@run-at document-start，好像只需要bliveproxy那邊有。
