### ISSUE TITLE
脚本无法使用 (與BLTH插件冲突)

### ISSUE THREAD

**Issue by Ponyonyope** [eric2788/tempermonkey-scripts#11]
**描述问题**
脚本没有任何提示，无法使用

**F12截图**
![屏幕截图 2022-08-31 222633](https://user-images.githubusercontent.com/63969532/187703438-a69f30e7-4d83-4a16-8a3d-18ecc5095191.png)

**你的配置**
 -Microsoft Edge
版本 104.0.1293.70 

-Google Chrome
版本 104.0.5112.102

 - 使用的插件版本 Tampermonkey  4.16.1

**额外补充**
edge和chrome都是一样的截图内容，无痕模式也试过，已排除其他插件冲突

补充你的内容

**Comment by eric2788** [comment]
第二行的訊息有沒有重複洗版？沒有那就代表沒有問題，能給我看看你的設定界面？

**Comment by Ponyonyope** [comment]
没有洗版，设定界面如下图
![无标题](https://user-images.githubusercontent.com/63969532/187909293-5b3f09eb-184c-4f0d-aa4b-f4761588fdda.png)

**Comment by eric2788** [comment]
我自己測試過沒有問題(彈幕高亮和進入通知), 請問無法使用是哪個地方？

**Comment by Ponyonyope** [comment]
弹幕和进入通知都没有，好奇怪

**Comment by Ponyonyope** [comment]
非常抱歉，经过再次排查，发现是与这个脚本冲突了
https://greasyfork.org/zh-CN/scripts/406048-b%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B
即使启用这个脚本，而不开启它的任何功能的情况下都会使我们的这个脚本失效

**Comment by eric2788** [comment]
這就不清楚了，他那個腳本複雜很多，不排除在websocket掛接上動了手腳，這邊無法處理

**Comment by eric2788** [comment]
> 這就不清楚了，他那個腳本複雜很多，不排除在websocket掛接上動了手腳，這邊無法處理

其冲突原因在于，BLTH 的插件直接使用了 hook 而没有检查先前有没有 bliveproxy 被加载，导致高亮用户插件的所有的 websocket handler 被清空

关键代码 ↓
https://github.com/andywang425/BLTH/blob/4f37ee87791aa2954813d0ed2fd8f6cda4dfb582/B%E7%AB%99%E7%9B%B4%E6%92%AD%E9%97%B4%E6%8C%82%E6%9C%BA%E5%8A%A9%E6%89%8B.js#L380

**Comment by eric2788** [comment]
若要消除BLTH插件对於 bliveproxy 的强制挂接
需要关闭下面两个东西 ( 转为 false)

```yaml
DANMU_MODIFY: false, // 修改弹幕
AUTO_CHECK_DANMU: false, // 检查弹幕是否发送成功
```

**Comment by Ponyonyope** [comment]
这俩功能我一直都是关闭的，我刚也检查了没有打开
![image](https://user-images.githubusercontent.com/63969532/189694993-c8719b4c-c38e-4667-827e-8c02dc925aa1.png)
这个脚本在自动弹幕签到的时候也会检测有没有弹幕发送成功，应该是这个默认功能占用了
但还是谢谢你！

**Comment by eric2788** [comment]
> 这俩功能我一直都是关闭的，我刚也检查了没有打开
> ![image](https://user-images.githubusercontent.com/63969532/189694993-c8719b4c-c38e-4667-827e-8c02dc925aa1.png)
> 这个脚本在自动弹幕签到的时候也会检测有没有弹幕发送成功，应该是这个默认功能占用了
> 但还是谢谢你！
> 

這個代碼應該是默認設定，真正儲存了的設定應該在別的地方存起來了
