### ISSUE TITLE
无法索取***的用户资讯 / 无法高亮弹幕

### ISSUE THREAD

**Issue by Black-nimi** [eric2788/tempermonkey-scripts#13]
win10 edge浏览器 火狐浏览器 0.7.18版本

一、无法索取***的用户资讯: "undefined" is not valid JSON
edge浏览器
两个设定网页均出现该问题
![网页捕获_23-3-2023_202721_eric2788 github io](https://user-images.githubusercontent.com/108390386/227210551-f5566639-caa3-4309-bf74-b6bd81dc4438.jpeg)
火狐浏览器正常

二、无法高亮标记用户弹幕
edge浏览器 火狐浏览器
进入直播间提醒正常，标记用户弹幕还是原色也没有括号id

**Comment by eric2788** [comment]
試試關掉adblock

**Comment by Black-nimi** [comment]
> 試試關掉adblock

edge浏览器用的是uBlock Origin 现在关了还是不行
火狐浏览器只有油猴、高亮一个插件 不行

**Comment by eric2788** [comment]
能看看 F12 的 控制台 嗎 看看錯誤

**Comment by Black-nimi** [comment]
> 能看看 F12 的 控制台 嗎 看看錯誤
咋看？edge的网页捕获没法截控制台 其他截图没法一图流
直接复制吗？

**Comment by Black-nimi** [comment]
> 能看看 F12 的 控制台 嗎 看看錯誤
咋看？edge的网页捕获没法截控制台 其他截图没法一图流
直接复制吗？

**Comment by Black-nimi** [comment]
我把自己也加进高亮去几个直播间试了试
泛式 33989 我 2311831 正常显示入场、高亮和括号id
内德维德 5424 NIYA阿布 685026 魔狼咪莉娅 24643640 只有入场没有高亮和括号id

设定界面倒是只剩下内德维德会显示无法索取90873的用户资讯

**Comment by eric2788** [comment]
> 我把自己也加进高亮去几个直播间试了试 泛式 33989 我 2311831 正常显示入场、高亮和括号id 内德维德 5424 NIYA阿布 685026 魔狼咪莉娅 24643640 只有入场没有高亮和括号id
> 
> 设定界面倒是只剩下内德维德会显示无法索取90873的用户资讯

我自己試了試，加 90873 沒有問題
你 console 那邊把 verbose/debug 打開 應該有 高亮彈幕用戶 的 詳細信息(包括每個人發的彈幕, 你看看有沒有自己)

**Comment by eric2788** [comment]
我現在沒辦法測試，不知道是不是海外不能發彈幕的原因，反正我聊天欄bug了

**Comment by eric2788** [comment]
> 咋看？edge的网页捕获没法截控制台 其他截图没法一图流
> 直接复制吗？

windows截圖或者qq截圖

**Comment by Black-nimi** [comment]
我的直播间 正常
![屏幕截图 2023-03-25 234901](https://user-images.githubusercontent.com/108390386/227727960-c05f724d-8542-48fc-b7fb-6e1653d8b4e3.png)
内德维德 5424 不行
![屏幕截图 2023-03-25 234823](https://user-images.githubusercontent.com/108390386/227727993-78322326-0c40-400f-bbc3-57a054fddb30.png)

**Comment by eric2788** [comment]
> 我的直播间 正常 ![屏幕截图 2023-03-25 234901](https://user-images.githubusercontent.com/108390386/227727960-c05f724d-8542-48fc-b7fb-6e1653d8b4e3.png) 内德维德 5424 不行 ![屏幕截图 2023-03-25 234823](https://user-images.githubusercontent.com/108390386/227727993-78322326-0c40-400f-bbc3-57a054fddb30.png)

就這麼看上去檢測是沒問題的，那可能是元素的問題，兩者直播間有分別嗎？（例如新版和舊版）

**Comment by Black-nimi** [comment]
两直播间设置是一样的，没有新旧版
主页倒是有新旧版，从两个版本点进去直播间F12是一样的
![屏幕截图 2023-03-26 135658](https://user-images.githubusercontent.com/108390386/227759835-1f6fa935-8475-4f75-87af-8bc28b593e66.png)
要说最近直播间有什么变化，那大概就是十天前网页全屏和全屏会自动显示礼物栏，需要手动点画质旁边的关闭礼物栏

**Comment by kirayomato** [comment]
我也无法高亮弹幕，但是标记用户发弹幕时的声音提示正常

**Comment by eric2788** [comment]
明天有空看看，上班日沒啥時間看

**Comment by eric2788** [comment]
我看了看
 '.danmaku-item-container' 元素還在

**Comment by eric2788** [comment]
無法高亮的彈幕的原因已經找到，貌似是bliveproxy沒有成功攔截改寫到彈幕

**Comment by eric2788** [comment]
v0.7.19 已更新，可以试试看 
@Black-nimi @kirayomato

**Comment by eric2788** [comment]
有問題再重開issue吧

**Comment by Black-nimi** [comment]
辛苦辛苦
要说还有什么问题的话
那就是右边弹幕栏不会显示括号
![网页捕获_13-4-2023_235013_live bilibili com](https://user-images.githubusercontent.com/108390386/231822597-e5357b68-109b-4b39-b757-108badda10e7.jpeg)

**Comment by eric2788** [comment]
> 辛苦辛苦 要说还有什么问题的话 那就是右边弹幕栏不会显示括号 ![网页捕获_13-4-2023_235013_live bilibili com](https://user-images.githubusercontent.com/108390386/231822597-e5357b68-109b-4b39-b757-108badda10e7.jpeg)

右邊的速度你能看得上也就不需要什麼高亮彈幕了吧

**Comment by Black-nimi** [comment]
因为我看直播时喜欢刷论坛、玩手机啥的
听到弹幕提示音会切回来看，如果是弹幕多的直播间滚动弹幕容易刷过去，右边弹幕有括号的话会方便很多

**Comment by Black-nimi** [comment]
发现了个新问题
高亮的人发了弹幕后
如果有人发了同样的弹幕也会变成高亮 也会带括号

**Comment by eric2788** [comment]
> 高亮的人发了弹幕后
> 如果有人发了同样的弹幕也会变成高亮 也会带括号

更新了

**Comment by Black-nimi** [comment]
辛苦了

**Comment by u2shana** [comment]
> > 高亮的人发了弹幕后
> > 如果有人发了同样的弹幕也会变成高亮 也会带括号
> 
> 更新了


0.7.20我这边无法高亮,回滚到0.7.19正常,但是这版本有那个重复弹幕bug

**Comment by eric2788** [comment]
> > > 高亮的人发了弹幕后
> > > 如果有人发了同样的弹幕也会变成高亮 也会带括号
> > 
> > 
> > 更新了
> 
> 0.7.20我这边无法高亮,回滚到0.7.19正常,但是这版本有那个重复弹幕bug

更新了
