### ISSUE TITLE
添加用户时提示访问权限不足

### ISSUE THREAD

**Issue by kirayomato** [eric2788/tempermonkey-scripts#15]
概率出现，重试几次以后才能添加成功
![image](https://github.com/eric2788/tempermonkey-scripts/assets/38139345/1f5dfa9b-7530-450a-9675-60032ee20638)

![image](https://github.com/eric2788/tempermonkey-scripts/assets/38139345/9030ee7f-052b-433a-bd65-c31d3bf89784)

**Comment by eric2788** [comment]
這個問題我應該修過了，版本確定最新？

**Comment by kirayomato** [comment]
> 這個問題我應該修過了，版本確定最新？

![image](https://github.com/eric2788/tempermonkey-scripts/assets/38139345/ee9c3768-c73a-44da-a1e4-307c7a18747c)
是最新的

**Comment by eric2788** [comment]
这个还有问题吗？

**Comment by kirayomato** [comment]
最近没怎么用，似乎是没再遇到过
