### ISSUE TITLE
点击开启录制经常无响应

### ISSUE THREAD

**Issue by mianhuacotton** [eric2788/tempermonkey-scripts#2]
出现直播间：https://live.bilibili.com/631?from=search&seid=8224865687946712946&spm_id_from=333.337.0.0

**Comment by eric2788** [comment]
用一用bug回報的那個模板開issue吧 我需要詳細的資訊

**Comment by eric2788** [comment]
跟著這個template描述一下

**描述问题**
清楚地描述问题

**如何导致**
步骤讲述如何导致问题:
1. 进入 '...'
2. 点进 '....'
3. 打开 '....'
4. 无法使用

**理应出现的运作**
描述一下正常的时候理应出现的结果是如何

**F12截图**
按下  F12 打開 Console  然后 截图

**你的配置**
 - 浏览器 [e.g. chrome, safari] 及版本
 - 使用的插件版本 [e.g. 22]

**额外补充**
补充你的内容

**Comment by eric2788** [comment]
我火狐瀏覽器，點了錄製放置十分鐘順便看了個三分鐘切片，錄製已經到了 300mb 以上，但還是沒什麼問題.....

**Comment by mianhuacotton** [comment]
额额额debug level是啥

**Comment by eric2788** [comment]
F12 打開 console 然後打開錯誤和警告的level就行，不用debug

**Comment by mianhuacotton** [comment]
不知道为啥打开F12就没法复现了，不打开F12的时候点开始录制基本都是无响应

**Comment by eric2788** [comment]
> 不知道为啥打开F12就没法复现了，不打开F12的时候点开始录制基本都是无响应

啊这？？这属于是玄学了

**Comment by mianhuacotton** [comment]
![图片](https://user-images.githubusercontent.com/94798662/145223358-6f7bf66b-bb28-42ad-82da-ef39eaf2aaa1.png)
真的是这样。。。打开f12就能看到录制已经开始这个状态，不打开f12的话点了完全没反应

**Comment by eric2788** [comment]
不太清楚，会不会是浏览器的一些设定？

**Comment by mianhuacotton** [comment]
用的火狐浏览器，默认设定没改过别的，不过装了几个不同的脚本
![图片](https://user-images.githubusercontent.com/94798662/145457382-6d5a5588-fd80-474c-80ad-4a917c72b1e8.png)

**Comment by eric2788** [comment]
玄，我也是火狐，就沒這個問題

**Comment by eric2788** [comment]
再有任何补充就告诉我吧

**Comment by lshldhs** [comment]
补充
![%~R{08_OLY%RJPBVN0WXYTQ](https://user-images.githubusercontent.com/101938271/159126353-03ee429d-4d84-46ac-ac36-36dde24ef493.png)
，
录制一小段时间后会自动结束

**Comment by lshldhs** [comment]
![图片](https://user-images.githubusercontent.com/101938271/159126429-8d275984-6f94-433f-b62b-21836f1a0969.png)
错误
![Uploading 4I3VP2IAU]]XXRB[URTP][T.png…]()
警告

**Comment by lshldhs** [comment]
![ZI ) BF3SB2 `N2G)E$Y A](https://user-images.githubusercontent.com/101938271/159126491-53fd1260-80e0-45f5-afae-08721e297cb8.png)
警告

**Comment by lshldhs** [comment]
录制时的直播间：https://live.bilibili.com/blanc/631
使用的浏览器：火狐

**Comment by eric2788** [comment]
> ![ZI ) BF3SB2 `N2G)E$Y A](https://user-images.githubusercontent.com/101938271/159126491-53fd1260-80e0-45f5-afae-08721e297cb8.png)
> 警告

看一下錯誤？

**Comment by eric2788** [comment]
看了看警告和錯誤，都不太關事

錄製一段時間自動結束的原因可能是推流不穩定
推流突然斷了一下導致畫面加載中，就會斷定為錄製完成

**Comment by lshldhs** [comment]
![CL0_8`WAUTF_`12G}6T96GY](https://user-images.githubusercontent.com/101938271/160245989-d82427b3-3196-4c55-8076-9b6fc7eea151.png)
点击开始录制报错

**Comment by eric2788** [comment]
> ![CL0_8`WAUTF_`12G}6T96GY](https://user-images.githubusercontent.com/101938271/160245989-d82427b3-3196-4c55-8076-9b6fc7eea151.png)
> 点击开始录制报错

這個問題我之後解決一下，目前暫時的解決辦法是f5

**Comment by eric2788** [comment]
已更新 0.7 版本，修复录制无反应问题

**Comment by eric2788** [comment]
如果0.7还是有问题就回复一下我会再开
