### ISSUE TITLE
添加部分新用户时会显示“无法索取 <uid> 的用户资讯: 风控校验失败”

### ISSUE THREAD

**Issue by Lizz218** [eric2788/tempermonkey-scripts#20]
添加部分新用户时会显示“无法索取 <uid> 的用户资讯: 风控校验失败”

![QQ截图20241201161659](https://github.com/user-attachments/assets/b07ba384-3cc9-4e00-b2bf-972a3e608ad7)

 - 浏览器 [edge  131.0.2903.70] 
 - 使用的插件版本 [0.7.24]

**Comment by eric2788** [comment]
可能b站又改簽名算法了，目前未有頭緒，我先加一個繞過索取用戶資訊強制加用戶的選項

**Comment by eric2788** [comment]
@Lizz218 已更新: 228d41aa190cf9cdc05a3d2c4f2fa3e9d73a335d (v0.7.25) 试试看

**Comment by Lizz218** [comment]
风控已经可以强制添加 但强制添加后显示为 无法索引用户资讯
![微信截图_20241202150613](https://github.com/user-attachments/assets/142a64da-ba67-4b02-87db-e42732584f9a)
![微信截图_20241202150622](https://github.com/user-attachments/assets/c2c951a1-9576-41d1-aa50-a36abcec9a60)

**Comment by eric2788** [comment]
> 风控已经可以强制添加 但强制添加后显示为 无法索引用户资讯 ![微信截图_20241202150613](https://private-user-images.githubusercontent.com/115460772/391442853-142a64da-ba67-4b02-87db-e42732584f9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjM1OTcsIm5iZiI6MTczMzEyMzI5NywicGF0aCI6Ii8xMTU0NjA3NzIvMzkxNDQyODUzLTE0MmE2NGRhLWJhNjctNGIwMi04N2RiLWU0MjczMjU4NGY5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQwNzA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjdjNzkwNmIyNTg3OGUyMzk5ODJjYjlmMzI3M2M4OWJmZjJjMmYzY2JhNWM3YWM1ZDE0MWMwY2MxZjk3MjNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._CmwctwbsMVv3DpWlnjavcRiZsm-cTnkq-t48IvEkOc) ![微信截图_20241202150622](https://private-user-images.githubusercontent.com/115460772/391442868-c2c951a1-9576-41d1-aa50-a36abcec9a60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjM1OTcsIm5iZiI6MTczMzEyMzI5NywicGF0aCI6Ii8xMTU0NjA3NzIvMzkxNDQyODY4LWMyYzk1MWExLTk1NzYtNDFkMS1hYTUwLWEzNmFiY2VjOWE2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQwNzA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzIwM2E3MTZmYTMzMjc3MTRjMzRmNDliMWMwOTBjODk5YTM4OWVmNzlhMDQ3MjMyNzUwZTg1ZTY3MjVjOTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kCFBayqJugJ640TOYC_NrDhNoFjB0DVo3fvnW9ChoEI)

正常，因爲繞過了索取用戶資訊。你看看能否正常高亮用戶就行

**Comment by eric2788** [comment]
另外我試了幾次發現有時候輸入正確的UID是可以索取到用戶資訊的 🤔

**Comment by Lizz218** [comment]
> > 风控已经可以强制添加 但强制添加后显示为 无法索引用户资讯 ![微信截图_20241202150613](https://private-user-images.githubusercontent.com/115460772/391442853-142a64da-ba67-4b02-87db-e42732584f9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjM1OTcsIm5iZiI6MTczMzEyMzI5NywicGF0aCI6Ii8xMTU0NjA3NzIvMzkxNDQyODUzLTE0MmE2NGRhLWJhNjctNGIwMi04N2RiLWU0MjczMjU4NGY5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQwNzA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjdjNzkwNmIyNTg3OGUyMzk5ODJjYjlmMzI3M2M4OWJmZjJjMmYzY2JhNWM3YWM1ZDE0MWMwY2MxZjk3MjNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._CmwctwbsMVv3DpWlnjavcRiZsm-cTnkq-t48IvEkOc) ![微信截图_20241202150622](https://private-user-images.githubusercontent.com/115460772/391442868-c2c951a1-9576-41d1-aa50-a36abcec9a60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjM1OTcsIm5iZiI6MTczMzEyMzI5NywicGF0aCI6Ii8xMTU0NjA3NzIvMzkxNDQyODY4LWMyYzk1MWExLTk1NzYtNDFkMS1hYTUwLWEzNmFiY2VjOWE2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQwNzA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzIwM2E3MTZmYTMzMjc3MTRjMzRmNDliMWMwOTBjODk5YTM4OWVmNzlhMDQ3MjMyNzUwZTg1ZTY3MjVjOTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kCFBayqJugJ640TOYC_NrDhNoFjB0DVo3fvnW9ChoEI)
> 
> 正常，因爲繞過了索取用戶資訊。你看看能否正常高亮用戶就行

试了一下 即便显示无法索取用户资讯 但可以正常高亮👍
