### ISSUE TITLE
第一次安装这个脚本，无法使用，在线人数不显示

### ISSUE THREAD

**Issue by SekiBetu** [eric2788/tempermonkey-scripts#4]
**描述问题**
脚本不显示，无法使用

**如何导致**
步骤讲述如何导致问题:
无法使用

**理应出现的运作**
直播间理应显示在线人数

**F12截图**
![image](https://user-images.githubusercontent.com/38283893/161387737-3a97c779-8c54-4beb-b747-dc770e522b0b.png)
![image](https://user-images.githubusercontent.com/38283893/161387744-8a7c2d08-f356-414c-9a5a-478ea5dbc253.png)

**你的配置**
 - Chrome 100.0.4896.60
 - 开源的暴力猴脚本管理器
 - 斗虫数据直播间可视化 0.4.12

**Comment by eric2788** [comment]
試試轉用 TamperMonkey?

https://www.tampermonkey.net/

**Comment by SekiBetu** [comment]
> 試試轉用 TamperMonkey?
> 
> [tampermonkey.net](https://www.tampermonkey.net/)

tampermonkey不开源啊，而且他会重复保存脚本，我导出的zip包里面一个脚本会按时间重复保存一堆，会让人感觉很脏，不是很想用，现在是只支持tampermonkey吗

**Comment by SekiBetu** [comment]
https://github.com/Tampermonkey/tampermonkey/issues/1190#issuecomment-808411189 这也是我不用tampermonkey的原因之一

**Comment by eric2788** [comment]
不太清楚是否支援暴力猴，因為我沒用過，目前腳本我現在運行是正常的
