### ISSUE TITLE
下载下来的flv文件放进格式工厂没法识别完整视频

### ISSUE THREAD

**Issue by lshldhs** [eric2788/tempermonkey-scripts#7]
**描述问题**
下载下来的flv文件放进格式工厂没法识别完整视频

**如何导致**
步骤讲述如何导致问题:
1. 录制直播视频
2. 将录制好的flv文件拖入格式工厂

**理应出现的运作**
能正常识别整个视频

**F12截图**
按下 F12 打開 Console 然后 截图
![图片](https://user-images.githubusercontent.com/101938271/169700418-9a507385-7452-4f80-b19b-e47b1c1697fe.png)
上面2分多钟的为直接录制的视频片段，下面的为迅雷影音二次裁剪后的视频，能完整识别视频
![图片](https://user-images.githubusercontent.com/101938271/169700520-07e2cf09-aa41-4ea3-8954-f254e37728c8.png)
![图片](https://user-images.githubusercontent.com/101938271/169700527-be982fc8-46c0-4990-a061-4fff2c36cb63.png)

**你的配置**
 - 浏览器 [e.g. chrome, safari] 及版本
 -![图片](https://user-images.githubusercontent.com/101938271/169700630-bdb06956-43c7-4983-851f-f140b7cedd7c.png)
 - 使用的插件版本 [e.g. 22]
![图片](https://user-images.githubusercontent.com/101938271/169700621-8f4eba26-f447-4de5-bc69-3524a3555599.png)

**额外补充**
补充你的内容

**Comment by eric2788** [comment]
那個flv檔案能發出來看看嗎

**Comment by lshldhs** [comment]
上方原视频，下放迅雷影音裁剪后视频



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eric2788/tempermonkey-scripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月22日(星期天) 晚上10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eric2788/tempermonkey-scripts] 下载下来的flv文件放进格式工厂没法识别完整视频 (Issue #7)





 
那個flv檔案能發出來看看嗎
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

早稻叽 - 明仔载.flv (189.45M, 2022年06月21日 22:37 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=716436351ef61a9543f21e2d4439004e5c050054525d075314050701031406515b001b0d5b5d574c0d520754040105560f560156622a32b5ded188ead6191f41fa93e1e5b6e11c0755123608&code=9d65b92a




早稻叽 - 明仔载20225222223241.flv (189.36M, 2022年06月21日 22:39 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=6632323901561ac44aa41a214462021f520153095b5405001d06075b514f040854511f585451521d0554000c51575108070b0100624330e4d7878ce6d6421d10f3c5e5e9b6ba02000200070b50500202030006084c045c46300f&code=0229bb00

**Comment by lshldhs** [comment]
github不支持flv文件，已qq邮箱发送

**Comment by eric2788** [comment]
下載下來的flv不能識別是正常的吧，因為這個腳本的stream flv在錄製中止時是即時切斷的，所以能播放但是沒有辦法識別時長之類的資訊，通常都是透過轉換(例如轉換mp4)之後才能完整識別視頻再進行下個動作。

**Comment by eric2788** [comment]
所以经过转换或者裁剪之后是正常了吗？如果是这样我就在页面那边加个提醒吧

**Comment by lshldhs** [comment]
转换后是正常的，就是没办法直接用格式工厂剪切了稍微麻烦点

**Comment by eric2788** [comment]
直接拉进去切应该是没办法hh，始终前端能做的video codec的东西很有限 ~~(加上懒得折腾)~~
