### ISSUE TITLE
老师好，高亮特定用户弹幕设定界面坏了

### ISSUE THREAD

**Issue by orrangee** [eric2788/tempermonkey-scripts#8]
![image](https://user-images.githubusercontent.com/104009963/172208280-e330991d-6539-40bd-9ca5-4d0e6e2d2f4a.png)

**Comment by eric2788** [comment]
試試國內節點？neeemooo那個

**Comment by orrangee** [comment]
> 試試國內節點？neeemooo那個

老师也是一样坏了
![image](https://user-images.githubusercontent.com/104009963/172367672-bd330641-db70-4867-adb2-3a077f570380.png)

**Comment by eric2788** [comment]
你看看能不能存取這個鏈接: [https://cdn.jsdelivr.net/npm/mdui@1.0.1/dist/css/mdui.min.css](view-source:https://cdn.jsdelivr.net/npm/mdui@1.0.1/dist/css/mdui.min.css)

**Comment by orrangee** [comment]
> 你看看能不能存取這個鏈接： https://cdn.jsdelivr.net/npm/mdui@1.0.1/dist/css/mdui.min.css

![image](https://user-images.githubusercontent.com/104009963/172369794-d969858a-7e3a-4a9e-9beb-471ffc96bbb6.png)
老师也不行QAQ

**Comment by eric2788** [comment]
恩，jsdeilver節點可能被墻了，我這邊是可以連接的
換別的瀏覽器也不行是嗎

**Comment by orrangee** [comment]
> https://cdn.jsdelivr.net/npm/mdui@1.0.1/dist/css/mdui.mi

> 恩，jsdeilver節點可能被墻了，我這邊是可以連接的 換別的瀏覽器也不行是嗎



> 恩，jsdeilver節點可能被墻了，我這邊是可以連接的 換別的瀏覽器也不行是嗎

是的老师，我换了chrome也是不行
![image](https://user-images.githubusercontent.com/104009963/172371070-cad9b15b-69b3-41c3-bc0d-8e2d309960db.png)

**Comment by eric2788** [comment]
我更新了CDN節點，現在試一次
https://eric2788.github.io/scriptsettings/highlight-user/

**Comment by orrangee** [comment]
> 所有者

太感谢老师了已经可以正常使用了！！
