### ISSUE TITLE
老师我又来了

### ISSUE THREAD

**Issue by orrangee** [eric2788/tempermonkey-scripts#9]
高亮他又没反应了
![image](https://user-images.githubusercontent.com/104009963/175305133-d7033529-0d04-45dc-b85f-19b105622c33.png)
![image](https://user-images.githubusercontent.com/104009963/175305158-b7dedd90-e19d-48da-a8b0-1065330854da.png)

**Comment by orrangee** [comment]
版本是0.7.18的

**Comment by eric2788** [comment]
失效的是腳本還是設定界面？

**Comment by orrangee** [comment]
> 失效的是腳本還是設定界面？

脚本

**Comment by eric2788** [comment]
腳本的什麼功能失靈？失靈的時候控制台報錯了啥？

**Comment by orrangee** [comment]
> 腳本的什麼功能失靈？失靈的時候控制台報錯了啥？

没有任何提示，弹幕和进入直播间，我感觉我是上次那个网址又打不开，然后造成通知不到

**Comment by eric2788** [comment]
你的设定网址有成功打开到吗？

**Comment by orrangee** [comment]
> 你的设定网址有成功打开到吗？

可以打开但是功能都没用，控制台报错也只有两个

**Comment by orrangee** [comment]
![image](https://user-images.githubusercontent.com/104009963/175311618-1442d180-1254-4810-bb69-c846d1a74cf4.png)

**Comment by eric2788** [comment]
你的浏览器是啥

**Comment by orrangee** [comment]
> 你的浏览器是啥

edge

**Comment by eric2788** [comment]
会不会是edge版本过旧？我自己用的edge没啥问题

设定界面都能加载列表和可以试听

**Comment by orrangee** [comment]
> 会不会是edge版本过旧？我自己用的edge没啥问题
> 
> 设定界面都能加载列表和可以试听

![image](https://user-images.githubusercontent.com/104009963/175315600-be92b4a8-90ce-48d2-91a5-2e824484e1d5.png)
会不会是因为我是win11？

**Comment by eric2788** [comment]
umm只看上面的兩個錯誤實在看不出什麼

**Comment by orrangee** [comment]
> umm只看上面的兩個錯誤實在看不出什麼
那就算了老师能帮我看看另外一个问题吗

**Comment by eric2788** [comment]
什么问题？

**Comment by orrangee** [comment]
也是高亮的是用机器人捕获的，我端口一直连接不上

**Comment by eric2788** [comment]
log呢？ 有按照readme的程序做？

**Comment by orrangee** [comment]
> log呢？ 有按照readme的程序做？

小白一个没怎么看懂所以想付费学习下怎么安装

**Comment by eric2788** [comment]
umm国内的支付渠道大概用不了

**Comment by orrangee** [comment]
> umm国内的支付渠道大概用不了

阿这。。。尬住了
